/*
 * This Java source file was auto generated by running 'gradle buildInit --type java-library'
 * by 'stefan' at '22.09.16 21:40' with Gradle 3.1
 *
 * @author stefan, @date 22.09.16 21:40
 */
public class Library {
    public boolean someLibraryMethod() {
        return true;
    }
}
